name: Node Keep Alive
on:
  schedule:
    - cron: '*/10 * * * *' # 每10分钟执行一次
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: 唤醒 Render 服务
        run: curl -s https://armbian-installer.onrender.com/video-fly > /dev/null
